export const FETCH_SEARCH_IMAGES_START = 'FETCH_SEARCH_IMAGES_START';
export const FETCH_SEARCH_IMAGES_SUCCESS = 'FETCH_SEARCH_IMAGES_SUCCESS';
export const FETCH_SEARCH_IMAGES_FAILURE = 'FETCH_SEARCH_IMAGES_FAILURE';

export const FETCH_LOAD_IMAGES_START = 'FETCH_LOAD_IMAGES_START';
export const FETCH_LOAD_IMAGES_SUCCESS = 'FETCH_LOAD_IMAGES_SUCCESS';
export const FETCH_LOAD_IMAGES_FAILURE = 'FETCH_LOAD_IMAGES_FAILURE';

export const FETCH_IMAGE_BY_ID_START = 'FETCH_IMAGE_BY_ID_START';
export const FETCH_IMAGE_BY_ID_SUCCESS = 'FETCH_IMAGE_BY_ID_SUCCESS';
export const FETCH_IMAGE_BY_ID_FAILURE = 'FETCH_IMAGE_BY_ID_FAILURE';