export const FETCH_IMAGES_START = 'FETCH_IMAGES_START';
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS';
export const FETCH_IMAGES_FAILURE = 'FETCH_IMAGES_FAILURE';

export const FETCH_SEARCH_IMAGES_START = 'FETCH_SEARCH_IMAGES_START';
export const FETCH_SEARCH_IMAGES_SUCCESS = 'FETCH_SEARCH_IMAGES_SUCCESS';
export const FETCH_SEARCH_IMAGES_FAILURE = 'FETCH_SEARCH_IMAGES_FAILURE';